#roll                      : Roll angle (rad) (float)     
#pitch                     : Pitch angle (rad) (float) 
#yaw                       : Yaw angle (rad) (float)
#rollspeed                 : Roll angular speed (rad/s) (float)
#pitchspeed                : Pitch angular speed (rad/s) (float)
#yawspeed                  : Yaw angular speed (rad/s) (float)    

float32 roll
float32 pitch
float32 yaw 
float32 rollspeed 
float32 pitchspeed
float32 yawspeed
